# Generated by Django 2.2.1 on 2019-05-30 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Item')),
                ('item_packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ItemPackaging')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('date_pick_up', models.DateField(blank=True, null=True)),
                ('place_of_pickup', models.CharField(max_length=100)),
                ('place_of_deliver', models.CharField(max_length=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Buyer')),
                ('order_items', models.ManyToManyField(to='invoices.OrderItem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Supplier')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Truck')),
                ('truck_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TruckDriver')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
